# redis-server.yml
version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 9000
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 9000:9000