name: green-grim-deploy-to-ec2

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./green

    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Spring-application build 
        run: ./gradlew build


      # Docker
      - name: Docker - Build and push for prod
        if: contains(github.ref, 'prod')
        run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker build -f Dockerfile-prod -t greengrim0919/green-grim-prod:latest .
          sudo docker push greengrim0919/green-grim-prod:latest

      - name: Docker - Build and push for dev
        if: contains(github.ref, 'develop')
        run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker build -f Dockerfile-dev -t greengrim0919/green-grim-dev:latest .
          sudo docker push greengrim0919/green-grim-dev:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 for prod
        if: contains(github.ref, 'main')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker system prune -f
            sudo docker pull greengrim0919/green-grim-prod:latest
            sudo docker stop green-grim-server && sudo docker rm green-grim-server
            sudo docker run -d --name green-grim-server -p 8080:8080 greengrim0919/green-grim-prod:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} green-grim-server | grep -v '^0'

      - name: Depoly in AWS ec2 for dev
        if: contains(github.ref, 'develop')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker system prune -f
            sudo docker pull greengrim0919/green-grim-dev:latest
            sudo docker stop green-grim-server-dev && sudo docker rm green-grim-server-dev
            sudo docker run -d --name green-grim-server-dev -p 8080:8080 greengrim0919/green-grim-dev:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} green-grim-server-dev | grep -v '^0'
