name: green-grim-deploy-to-ec2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./green

    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Spring-application build 
        run: ./gradlew build


      # Docker
      - name: Docker - Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./green
          push: true
          tags: leeyeonsang/green-grim:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker system prune -f
            sudo docker pull leeyeonsang/green-grim:latest
            sudo docker stop green-grim-server && sudo docker rm green-grim-server
            sudo docker run -d --name green-grim-server -p 8080:8080 leeyeonsang/green-grim:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} green-grim-serverr | grep -v '^0'
